(async()=>{
  const base=process.env.TEST_BASE_URL||'http://127.0.0.1:3193';
  const form=async(path,cookie,values)=>fetch(base+path,{method:'POST',redirect:'manual',headers:{cookie,'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(values)});
  let response=await fetch(base+'/list-your-supermarket'),html=await response.text();
  const cookie=response.headers.get('set-cookie').split(';')[0],csrf=html.match(/name="_csrf" value="([^"]+)/)[1],email=`floor-${Date.now()}@example.test`;
  response=await form('/list-your-supermarket',cookie,{_csrf:csrf,name:'Floor Owner',email,password:'StrongPassword123',supermarketName:'Floor Market',address:'Test Road',phone:''});html=await response.text();
  const code=html.match(/Development code: <b>(\d{6})<\/b>/)[1],verifyCsrf=html.match(/name="_csrf" value="([^"]+)/)[1];
  response=await form('/verify',cookie,{_csrf:verifyCsrf,email,code});if(response.status!==302)throw new Error('Verification failed');
  response=await fetch(base+'/workspace',{headers:{cookie}});html=await response.text();if(response.status!==200||!html.includes('VISUAL EDITOR')||!html.includes('Supermarket workspace')||!html.includes('data-go-back'))throw new Error(`Workspace did not render (${response.status})`);
  const workspaceCsrf=html.match(/name="_csrf" value="([^"]+)/)[1],slug=html.match(/href="\/supermarkets\/([^"]+)"/)[1];
  await form('/workspace/aisles',cookie,{_csrf:workspaceCsrf,code:'A1',name:'Dairy',kind:'aisle',width:'180',height:'360'});
  response=await fetch(base+'/workspace#layout',{headers:{cookie}});html=await response.text();const aisleId=html.match(/data-aisle-id="([^"]+)"/)[1],csrf2=html.match(/name="_csrf" value="([^"]+)/)[1];
  await form(`/workspace/aisles/${aisleId}/sections`,cookie,{_csrf:csrf2,name:'Milk section',side:'front',startPercent:'0',endPercent:'50'});
  response=await fetch(base+'/workspace',{headers:{cookie}});html=await response.text();const sectionId=html.match(/<option value="([^"]+)" data-aisle="[^"]+" data-side="front">Milk section<\/option>/)[1],csrf3=html.match(/name="_csrf" value="([^"]+)/)[1];
  await form('/workspace/entrances',cookie,{_csrf:csrf3,name:'Main entrance',x:'40',y:'700'});
  await form('/workspace/products',cookie,{_csrf:csrf3,name:'Full Cream Milk 2L',category:'Dairy',sku:'MILK2',barcode:'',price:'34.99',stock:'20',aisleId,sectionId,aisleSide:'front',bay:'2',shelf:'Eye level'});
  response=await fetch(base+'/workspace/products/import-template',{headers:{cookie}});if(response.status!==200||!(await response.text()).includes('Product Name,Barcode'))throw new Error('CSV template failed');
  response=await fetch(base+'/workspace/products/import',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({_csrf:csrf3,rows:[{name:'Long Grain Rice 2kg',barcode:'600100000002',sku:'RICE2',category:'Pantry',price:'49.99',stock:'12',available:'yes',aisleCode:'A1',side:'front',section:'Milk section',bay:'3',shelf:'Middle'}]})});const imported=await response.json();if(response.status!==200||imported.created!==1)throw new Error('Catalogue import failed');
  response=await fetch(base+'/workspace/products/import',{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({_csrf:csrf3,rows:[{name:'Long Grain Rice 2kg',barcode:'600100000002',sku:'RICE2',category:'Pantry',price:'47.99',stock:'15',available:'yes',aisleCode:'A1',side:'front',section:'Milk section',bay:'3',shelf:'Middle'}]})});const updatedImport=await response.json();if(response.status!==200||updatedImport.updated!==1)throw new Error('Safe catalogue update failed');
  const publicResponse=await fetch(base+`/supermarkets/${slug}`),publicHtml=await publicResponse.text();if(publicResponse.status!==200||!publicHtml.includes('Customer navigation')||!publicHtml.includes('Store map'))throw new Error('Public customer navigation did not render');
  response=await fetch(base+`/supermarkets/${slug}`,{headers:{cookie}});html=await response.text();if(response.status!==200||!html.includes('Full Cream Milk 2L')||!html.includes('Paste your shopping list'))throw new Error('Customer matcher did not render');
  const customerCsrf=html.match(/data-csrf="([^"]+)"/)[1],entranceId=html.match(/<option value="([^"]+)">Main entrance<\/option>/)[1],productData=JSON.parse(html.match(/<script type="application\/json" id="productData">([\s\S]*?)<\/script>/)[1]),productId=productData.find(x=>x.name==='Full Cream Milk 2L').id,riceId=productData.find(x=>x.name==='Long Grain Rice 2kg').id;
  await form('/workspace/products/bulk-location',cookie,{_csrf:csrf3,productIds:riceId,aisleId,aisleSide:'front',sectionId});
  response=await fetch(base+`/api/supermarkets/${slug}/search-events`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({_csrf:customerCsrf,sessionId:'test-shopper',searches:[{query:'milk',matchCount:1},{query:'dragon fruit',matchCount:0}]})});if(response.status!==200)throw new Error(`Search analytics failed: ${response.status}`);
  response=await fetch(base+`/api/supermarkets/${slug}/route`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({_csrf:customerCsrf,sessionId:'test-shopper',entranceId,productIds:[productId]})});if(response.status!==200)throw new Error(`Customer route failed: ${response.status}`);
  response=await fetch(base+`/api/supermarkets/${slug}/feedback`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({_csrf:customerCsrf,sessionId:'test-shopper',eventType:'found',productId})});if(response.status!==200)throw new Error('Found feedback failed');
  response=await fetch(base+`/api/supermarkets/${slug}/feedback`,{method:'POST',headers:{cookie,'content-type':'application/json'},body:JSON.stringify({_csrf:customerCsrf,sessionId:'test-shopper',eventType:'route_complete'})});if(response.status!==200)throw new Error('Completion feedback failed');
  response=await fetch(base+'/workspace#analytics',{headers:{cookie}});html=await response.text();if(!html.includes('dragon fruit')||!html.includes('Shopper insights'))throw new Error('Demand analytics did not render');
  await form(`/workspace/sections/${sectionId}/delete`,cookie,{_csrf:csrf3});
  await form(`/workspace/entrances/${entranceId}/delete`,cookie,{_csrf:csrf3});
  await form(`/workspace/aisles/${aisleId}/delete`,cookie,{_csrf:csrf3});
  response=await fetch(base+'/workspace#layout',{headers:{cookie}});html=await response.text();if(html.includes(`data-aisle-id="${aisleId}"`)||html.includes('Main entrance</b>'))throw new Error('Floor deletion controls failed');
  console.log('Floor editor, catalogue import, bulk location, feedback analytics and customer route passed');
})().catch(error=>{console.error(error);process.exit(1)});
