const express=require('express');
const bcrypt=require('bcryptjs');
const {rateLimit}=require('express-rate-limit');
const {z}=require('zod');
const db=require('../config/db');
const config=require('../config');
const {send}=require('../utils/email');
const {id,slug,randomToken,tokenHash}=require('../utils/security');
const router=express.Router();
const limiter=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:'draft-7',legacyHeaders:false});
const password=z.string().min(12).regex(/[A-Z]/).regex(/[a-z]/).regex(/[0-9]/);
const expires=minutes=>new Date(Date.now()+minutes*60000).toISOString();
async function audit(req,user,action,metadata={}){await db.run('INSERT INTO audit_logs(id,supermarket_id,user_id,action,metadata,ip) VALUES(?,?,?,?,?,?)',[id(),user?.supermarket_id||null,user?.id||null,action,JSON.stringify(metadata),req.ip])}
async function verification(user){const code=String(Math.floor(100000+Math.random()*900000));await db.run('INSERT INTO auth_tokens(id,user_id,type,token_hash,expires_at) VALUES(?,?,?,?,?)',[id(),user.id,'verify-email',tokenHash(code),expires(30)]);await send({to:user.email,subject:'Verify your Semausu account',text:`Your verification code is ${code}. It expires in 30 minutes.`});return code}
router.get('/list-your-supermarket',(_req,res)=>res.render('owner-signup',{title:'Register your supermarket'}));
router.post('/list-your-supermarket',limiter,async(req,res)=>{const parsed=z.object({name:z.string().min(2).max(80),email:z.string().email(),password,supermarketName:z.string().min(2).max(120),address:z.string().max(200),phone:z.string().max(30)}).safeParse(req.body);if(!parsed.success)return res.status(400).render('owner-signup',{title:'Register your supermarket',error:'Check your details. Passwords need 12 characters, uppercase, lowercase and a number.'});const b=parsed.data,email=b.email.toLowerCase();if(await db.get('SELECT id FROM users WHERE email=?',[email]))return res.status(409).render('owner-signup',{title:'Register your supermarket',error:'That email is already registered.'});const storeId=id(),userId=id(),storeSlug=`${slug(b.supermarketName)}-${randomToken(3).toLowerCase()}`;await db.run('INSERT INTO supermarkets(id,name,slug,address,phone) VALUES(?,?,?,?,?)',[storeId,b.supermarketName,storeSlug,b.address,b.phone]);await db.run("INSERT INTO users(id,supermarket_id,name,email,password_hash,role) VALUES(?,?,?,?,?,'owner')",[userId,storeId,b.name,email,await bcrypt.hash(b.password,12)]);const user={id:userId,supermarket_id:storeId,email};const code=await verification(user);await audit(req,user,'Supermarket owner registered');res.render('verify',{title:'Verify your email',email,devCode:config.production?null:code});});
router.get('/verify',(_req,res)=>res.render('verify',{title:'Verify your email',email:'',devCode:null}));
router.post('/verify',limiter,async(req,res)=>{const email=String(req.body.email||'').toLowerCase(),code=String(req.body.code||''),user=await db.get('SELECT * FROM users WHERE email=?',[email]);if(!user)return res.status(400).render('verify',{title:'Verify your email',email,error:'Invalid or expired code.',devCode:null});const token=await db.get("SELECT * FROM auth_tokens WHERE user_id=? AND type='verify-email' AND token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP ORDER BY created_at DESC LIMIT 1",[user.id,tokenHash(code)]);if(!token)return res.status(400).render('verify',{title:'Verify your email',email,error:'Invalid or expired code.',devCode:null});await db.run("UPDATE users SET email_verified=1,status='active' WHERE id=?",[user.id]);await db.run("UPDATE supermarkets SET status='active' WHERE id=? AND status='pending'",[user.supermarket_id]);await db.run('UPDATE auth_tokens SET used_at=CURRENT_TIMESTAMP WHERE id=?',[token.id]);req.session.userId=user.id;res.redirect('/workspace');});
router.get(config.staffPortalPath,(req,res)=>res.render('login',{title:'Team access',portal:config.staffPortalPath,platform:false}));
router.post(config.staffPortalPath+'/login',limiter,async(req,res)=>login(req,res,false));
router.get(config.staffPortalPath+'/forgot',(_req,res)=>res.render('forgot',{title:'Reset password',portal:config.staffPortalPath}));
router.post(config.staffPortalPath+'/forgot',limiter,async(req,res)=>forgot(req,res,config.staffPortalPath,false));
router.get(config.platformPortalPath,(req,res)=>res.render('login',{title:'Platform access',portal:config.platformPortalPath,platform:true}));
router.post(config.platformPortalPath+'/login',limiter,async(req,res)=>login(req,res,true));
router.get(config.platformPortalPath+'/forgot',(_req,res)=>res.render('forgot',{title:'Reset password',portal:config.platformPortalPath}));
router.post(config.platformPortalPath+'/forgot',limiter,async(req,res)=>forgot(req,res,config.platformPortalPath,true));
async function login(req,res,platform){const email=String(req.body.email||'').toLowerCase(),user=await db.get('SELECT * FROM users WHERE email=?',[email]),valid=user&&user.password_hash&&await bcrypt.compare(String(req.body.password||''),user.password_hash),isPlatform=user?.role.startsWith('platform_');if(!valid||user.status!=='active'||!user.email_verified||isPlatform!==platform){await new Promise(resolve=>setTimeout(resolve,300));return res.status(401).render('login',{title:platform?'Platform access':'Team access',portal:platform?config.platformPortalPath:config.staffPortalPath,platform,error:'Invalid credentials.'})}req.session.userId=user.id;await db.run('UPDATE users SET last_login_at=CURRENT_TIMESTAMP WHERE id=?',[user.id]);await audit(req,user,'Signed in');res.redirect(platform?'/platform':'/workspace')}
async function forgot(req,res,portal,platform){const email=String(req.body.email||'').toLowerCase(),user=await db.get('SELECT * FROM users WHERE email=? AND status=\'active\' AND email_verified=1',[email]);if(user&&user.role.startsWith('platform_')===platform){const raw=randomToken();await db.run('INSERT INTO auth_tokens(id,user_id,type,token_hash,expires_at) VALUES(?,?,?,?,?)',[id(),user.id,'reset-password',tokenHash(raw),expires(30)]);await send({to:user.email,subject:'Reset your Semausu password',text:`Reset your password within 30 minutes: ${config.appUrl}/reset-password/${raw}`})}res.render('forgot',{title:'Reset password',portal,sent:true})}
router.get('/reset-password/:token',async(req,res)=>{const token=await db.get("SELECT * FROM auth_tokens WHERE type='reset-password' AND token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP",[tokenHash(req.params.token)]);res.render('reset',{title:'Create new password',token:req.params.token,valid:Boolean(token)});});
router.post('/reset-password/:token',limiter,async(req,res)=>{const token=await db.get("SELECT * FROM auth_tokens WHERE type='reset-password' AND token_hash=? AND used_at IS NULL AND expires_at>CURRENT_TIMESTAMP",[tokenHash(req.params.token)]),parsed=password.safeParse(req.body.password);if(!token||!parsed.success)return res.status(400).render('reset',{title:'Create new password',token:req.params.token,valid:Boolean(token),error:'The link expired or the password is not strong enough.'});await db.run('UPDATE users SET password_hash=? WHERE id=?',[await bcrypt.hash(parsed.data,12),token.user_id]);await db.run('UPDATE auth_tokens SET used_at=CURRENT_TIMESTAMP WHERE id=?',[token.id]);res.render('reset',{title:'Password updated',token:req.params.token,valid:false,complete:true});});
router.post('/logout',(req,res)=>req.session.destroy(()=>res.redirect('/')));
router.get('/join/:token',async(req,res)=>{const invite=await db.get("SELECT * FROM invitations WHERE token_hash=? AND accepted_at IS NULL AND expires_at>CURRENT_TIMESTAMP",[tokenHash(req.params.token)]);res.render('accept-invite',{title:'Accept invitation',token:req.params.token,invite});});
router.post('/join/:token',limiter,async(req,res)=>{const invite=await db.get("SELECT * FROM invitations WHERE token_hash=? AND accepted_at IS NULL AND expires_at>CURRENT_TIMESTAMP",[tokenHash(req.params.token)]);if(!invite)return res.status(400).render('error',{title:'Invitation expired',message:'Ask your administrator for a new invitation.'});const parsed=z.object({name:z.string().min(2),password}).safeParse(req.body);if(!parsed.success)return res.status(400).render('accept-invite',{title:'Accept invitation',token:req.params.token,invite,error:'Use a strong password with at least 12 characters.'});if(await db.get('SELECT id FROM users WHERE email=?',[invite.email]))return res.status(409).render('error',{title:'Account exists',message:'Use the team login page.'});const userId=id();await db.run('INSERT INTO users(id,supermarket_id,name,email,password_hash,role,status,email_verified) VALUES(?,?,?,?,?,?,?,1)',[userId,invite.supermarket_id,parsed.data.name,invite.email,await bcrypt.hash(parsed.data.password,12),invite.role,'active']);await db.run('UPDATE invitations SET accepted_at=CURRENT_TIMESTAMP WHERE id=?',[invite.id]);const portal=invite.role.startsWith('platform_')?config.platformPortalPath:config.staffPortalPath;res.render('invite-complete',{title:'Account verified',portal});});
module.exports=router;
