const express=require('express');
const {z}=require('zod');
const db=require('../config/db');
const config=require('../config');
const {requireUser,roles}=require('../middleware/auth');
const {id,randomToken,tokenHash}=require('../utils/security');
const {send}=require('../utils/email');
const router=express.Router();router.use(requireUser);router.use(roles('owner','manager','staff'));
async function data(storeId){const [store,products,aisles,entrances,team,tickets]=await Promise.all([db.get('SELECT * FROM supermarkets WHERE id=?',[storeId]),db.all('SELECT p.*,a.code aisle_code FROM products p LEFT JOIN aisles a ON a.id=p.aisle_id WHERE p.supermarket_id=? ORDER BY p.name',[storeId]),db.all('SELECT * FROM aisles WHERE supermarket_id=? ORDER BY sort_order,code',[storeId]),db.all('SELECT * FROM entrances WHERE supermarket_id=? ORDER BY sort_order',[storeId]),db.all("SELECT id,name,email,role,status,last_login_at FROM users WHERE supermarket_id=? ORDER BY role,name",[storeId]),db.all('SELECT * FROM support_tickets WHERE supermarket_id=? ORDER BY created_at DESC',[storeId])]);return{store,products,aisles,entrances,team,tickets}}
router.get('/',async(req,res)=>res.render('workspace',{title:'Store workspace',...(await data(req.user.supermarket_id))}));
router.post('/products',roles('owner','manager','staff'),async(req,res)=>{const b=z.object({name:z.string().min(1),category:z.string().default('General'),sku:z.string().default(''),barcode:z.string().default(''),price:z.coerce.number().min(0),stock:z.coerce.number().int().min(0),aisleId:z.string().optional(),bay:z.coerce.number().int().min(1),shelf:z.string().default('Eye level'),x:z.coerce.number().min(0),y:z.coerce.number().min(0)}).parse(req.body);await db.run('INSERT INTO products(id,supermarket_id,aisle_id,name,category,sku,barcode,price,stock,bay,shelf,x,y) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',[id(),req.user.supermarket_id,b.aisleId||null,b.name,b.category,b.sku,b.barcode,b.price,b.stock,b.bay,b.shelf,b.x,b.y]);res.redirect('/workspace#products')});
router.post('/products/:id/delete',roles('owner','manager'),async(req,res)=>{await db.run('DELETE FROM products WHERE id=? AND supermarket_id=?',[req.params.id,req.user.supermarket_id]);res.redirect('/workspace#products')});
router.post('/aisles',roles('owner','manager'),async(req,res)=>{const b=z.object({code:z.string().min(1).max(12),name:z.string().min(2),kind:z.enum(['aisle','department','service']),x:z.coerce.number().min(0),y:z.coerce.number().min(0),width:z.coerce.number().positive(),height:z.coerce.number().positive()}).parse(req.body);await db.run('INSERT INTO aisles(id,supermarket_id,code,name,kind,x,y,width,height) VALUES(?,?,?,?,?,?,?,?,?)',[id(),req.user.supermarket_id,b.code.toUpperCase(),b.name,b.kind,b.x,b.y,b.width,b.height]);res.redirect('/workspace#layout')});
router.post('/entrances',roles('owner','manager'),async(req,res)=>{const b=z.object({name:z.string().min(2),x:z.coerce.number().min(0),y:z.coerce.number().min(0)}).parse(req.body);await db.run('INSERT INTO entrances(id,supermarket_id,name,x,y) VALUES(?,?,?,?,?)',[id(),req.user.supermarket_id,b.name,b.x,b.y]);res.redirect('/workspace#layout')});
router.post('/team/invite',roles('owner','manager'),async(req,res)=>{const allowed=req.user.role==='owner'?['manager','staff']:['staff'],role=String(req.body.role);if(!allowed.includes(role))return res.status(403).render('error',{title:'Access denied',message:'You cannot invite that role.'});const email=String(req.body.email||'').toLowerCase();if(await db.get('SELECT id FROM users WHERE email=?',[email]))return res.status(409).render('error',{title:'Account exists',message:'That email is already registered.'});const raw=randomToken(),inviteId=id();await db.run('INSERT INTO invitations(id,supermarket_id,invited_by,email,role,token_hash,expires_at) VALUES(?,?,?,?,?,?,?)',[inviteId,req.user.supermarket_id,req.user.id,email,role,tokenHash(raw),new Date(Date.now()+48*3600000).toISOString()]);await send({to:email,subject:'Join your supermarket on Semausu',text:`You were invited as ${role}. Accept within 48 hours: ${config.appUrl}/join/${raw}`});res.redirect('/workspace#team')});
router.post('/team/:id/status',roles('owner','manager'),async(req,res)=>{const target=await db.get('SELECT * FROM users WHERE id=? AND supermarket_id=?',[req.params.id,req.user.supermarket_id]);if(!target||target.role==='owner'||(req.user.role==='manager'&&target.role==='manager'))return res.status(403).render('error',{title:'Access denied',message:'You cannot change this account.'});await db.run('UPDATE users SET status=? WHERE id=?',[req.body.status==='active'?'active':'suspended',target.id]);res.redirect('/workspace#team')});
router.post('/settings',roles('owner','manager'),async(req,res)=>{await db.run('UPDATE supermarkets SET name=?,address=?,phone=?,map_width=?,map_height=? WHERE id=?',[String(req.body.name),String(req.body.address||''),String(req.body.phone||''),Math.max(600,Number(req.body.mapWidth)||1200),Math.max(400,Number(req.body.mapHeight)||760),req.user.supermarket_id]);res.redirect('/workspace#settings')});
router.post('/support',async(req,res)=>{await db.run('INSERT INTO support_tickets(id,supermarket_id,user_id,subject,description,priority) VALUES(?,?,?,?,?,?)',[id(),req.user.supermarket_id,req.user.id,String(req.body.subject),String(req.body.description),['low','normal','high','critical'].includes(req.body.priority)?req.body.priority:'normal']);res.redirect('/workspace#support')});
module.exports=router;
