const {clearSegment}=require('./pathfinder');
const distance=(a,b)=>Math.hypot(Number(a.x)-Number(b.x),Number(a.y)-Number(b.y));
const pointKey=point=>`${Math.round(point.x)},${Math.round(point.y)}`;
const inside=(point,obstacles,gap=12)=>obstacles.some(item=>point.x>=Number(item.x)-gap&&point.x<=Number(item.x)+Number(item.width)+gap&&point.y>=Number(item.y)-gap&&point.y<=Number(item.y)+Number(item.height)+gap);

function checkoutApproach(checkout,gap=36){const x=Number(checkout.x),y=Number(checkout.y),width=Number(checkout.width),height=Number(checkout.height);if(checkout.approach_side==='back')return{x:x+width/2,y:y+height+gap};if(checkout.approach_side==='left')return{x:x-gap,y:y+height/2};if(checkout.approach_side==='right')return{x:x+width+gap,y:y+height/2};return{x:x+width/2,y:y-gap}}
function productApproach(fixture,side='front',bay=1,section=null,gap=32){const start=section?Number(section.start_percent)/100:0,end=section?Number(section.end_percent)/100:1,ratio=Math.min(.96,Math.max(.04,section?(start+end)/2:(((Number(bay)-1)%10)+.5)/10)),x=Number(fixture.x),y=Number(fixture.y),width=Number(fixture.width),height=Number(fixture.height);if(side==='back')return{x:x+width*ratio,y:y+height+gap,facing_direction:'up'};if(side==='left')return{x:x-gap,y:y+height*ratio,facing_direction:'right'};if(side==='right')return{x:x+width+gap,y:y+height*ratio,facing_direction:'left'};return{x:x+width*ratio,y:y-gap,facing_direction:'down'}}

function generateNetwork(obstacles,width,height,anchors=[]){const margin=24,gap=42,xs=new Set([margin,Number(width)-margin]),ys=new Set([margin,Number(height)-margin]);for(const item of obstacles){xs.add(Math.max(margin,Number(item.x)-gap));xs.add(Math.min(Number(width)-margin,Number(item.x)+Number(item.width)+gap));ys.add(Math.max(margin,Number(item.y)-gap));ys.add(Math.min(Number(height)-margin,Number(item.y)+Number(item.height)+gap))}for(const anchor of anchors){xs.add(Math.max(margin,Math.min(Number(width)-margin,Math.round(Number(anchor.x)))));ys.add(Math.max(margin,Math.min(Number(height)-margin,Math.round(Number(anchor.y)))))}const xValues=[...xs].sort((a,b)=>a-b),yValues=[...ys].sort((a,b)=>a-b),nodes=[],byKey=new Map();for(const x of xValues)for(const y of yValues){const point={x:Math.round(x),y:Math.round(y)};if(inside(point,obstacles))continue;point.key=pointKey(point);byKey.set(point.key,point);nodes.push(point)}const edges=[];for(const y of yValues){const row=nodes.filter(node=>node.y===Math.round(y)).sort((a,b)=>a.x-b.x);for(let index=1;index<row.length;index++)if(clearSegment(row[index-1],row[index],obstacles,16))edges.push({from:row[index-1],to:row[index],distance:distance(row[index-1],row[index])})}for(const x of xValues){const column=nodes.filter(node=>node.x===Math.round(x)).sort((a,b)=>a.y-b.y);for(let index=1;index<column.length;index++)if(clearSegment(column[index-1],column[index],obstacles,16))edges.push({from:column[index-1],to:column[index],distance:distance(column[index-1],column[index])})}return{nodes,edges}}

function nearestNode(point,nodes){return nodes.filter(node=>node.status!=='closed').sort((a,b)=>distance(point,a)-distance(point,b))[0]||null}
function graphPath(start,end,nodes,edges){if(!nodes.length||!edges.length)return[];const source=nearestNode(start,nodes),target=nearestNode(end,nodes);if(!source||!target)return[];const adjacency=new Map(nodes.map(node=>[node.id,[]]));for(const edge of edges.filter(item=>item.status!=='closed'&&Number(item.customer_allowed)!==0)){adjacency.get(edge.from_node_id)?.push({id:edge.to_node_id,cost:Number(edge.distance)});if(edge.direction==='both'||edge.direction==='backward')adjacency.get(edge.to_node_id)?.push({id:edge.from_node_id,cost:Number(edge.distance)})}const open=[source.id],cost=new Map([[source.id,0]]),came=new Map(),nodeById=new Map(nodes.map(node=>[node.id,node]));while(open.length){open.sort((a,b)=>(cost.get(a)+distance(nodeById.get(a),target))-(cost.get(b)+distance(nodeById.get(b),target)));const current=open.shift();if(current===target.id){const result=[];let cursor=current;while(cursor){result.push(nodeById.get(cursor));cursor=came.get(cursor)}return[{x:Number(start.x),y:Number(start.y)},...result.reverse().map(node=>({x:Number(node.x),y:Number(node.y)})),{x:Number(end.x),y:Number(end.y)}].filter((point,index,array)=>!index||pointKey(point)!==pointKey(array[index-1]))}for(const next of adjacency.get(current)||[]){const candidate=cost.get(current)+next.cost;if(candidate<(cost.get(next.id)??Infinity)){cost.set(next.id,candidate);came.set(next.id,current);if(!open.includes(next.id))open.push(next.id)}}}return[]}
module.exports={checkoutApproach,productApproach,generateNetwork,nearestNode,graphPath,distance};
